# Basic AIQ Configuration for Grid Optimization
# Simple setup with minimal dependencies

general:
  use_uvloop: true

# Available functions
functions:
  current_datetime:
    _type: current_datetime
  optimize_grid:
    _type: optimize_grid
  show_last_optimization:
    _type: show_last_optimization

# Basic LLM configuration (requires OPENAI_API_KEY)
llms:
  grid_llm:
    _type: openai
    model_name: gpt-4o-mini
    temperature: 0.1
    max_tokens: 1024

# Main workflow
workflow:
  _type: react_agent
  tool_names:
    - optimize_grid
    - show_last_optimization
    - current_datetime
  llm_name: grid_llm
  verbose: true
  system_message: |
    You are a grid optimization assistant. You can:
    1. Optimize grid supply for any region using optimize_grid
    2. Show the latest optimization results using show_last_optimization
    
    Available regions: us-west, us-east, us-central, pgae