# SPDX-FileCopyrightText: Copyright (c) 2024-2025, Grid Optimization Project
# SPDX-License-Identifier: Apache-2.0

# Advanced reasoning configuration for complex grid optimization scenarios

general:
  use_uvloop: true

# LLM Configuration for reasoning tasks
llms:
  reasoning_llm:
    _type: openai
    model_name: gpt-4o
    max_tokens: 8192
    temperature: 0.0  # Lower temperature for more deterministic reasoning
    
  analysis_llm:
    _type: openai  
    model_name: gpt-4o-mini
    max_tokens: 4096
    temperature: 0.1

# Grid Optimization Functions
functions:
  grid_optimize:
    _type: grid_optimize
  grid_status:
    _type: grid_status
  grid_analyze:
    _type: grid_analyze
  current_datetime:
    _type: current_datetime

# Reasoning Agent Workflow
workflow:
  _type: reasoning_agent
  tool_names:
    - grid_optimize
    - grid_status
    - grid_analyze
    - current_datetime
  llm_name: reasoning_llm
  max_iterations: 12
  verbose: true
  reasoning_model_name: analysis_llm
  
  # Enhanced system message for reasoning
  system_message: |
    You are an expert power grid optimization specialist with advanced analytical capabilities.
    
    For complex grid optimization scenarios, follow this reasoning process:
    
    1. ANALYSIS PHASE:
       - Assess current grid conditions and constraints
       - Identify optimization objectives and trade-offs
       - Consider safety, regulatory, and environmental factors
       
    2. PLANNING PHASE:
       - Develop multiple optimization strategies
       - Evaluate potential risks and benefits
       - Prioritize actions based on impact and feasibility
       
    3. EXECUTION PHASE:
       - Implement optimizations in a controlled manner
       - Monitor results and adjust parameters as needed
       - Document changes and performance improvements
       
    4. VALIDATION PHASE:
       - Verify optimization results meet requirements
       - Check for unintended consequences
       - Prepare recommendations for future improvements
    
    Always explain your reasoning process and provide justification for optimization decisions.
    Consider both immediate benefits and long-term grid stability.