# Advanced Grid Optimization Configuration
# Comprehensive NAT configuration with multiple grid optimization functions  
# Status: ⚠️ Requires OpenAI API key for LLM features
# Features: optimize_grid, show_last_optimization, current_datetime

general:
  use_uvloop: true

# Available functions
functions:
  current_datetime:
    _type: current_datetime
  optimize_grid:
    _type: nat_toolkit/optimize_grid
  show_last_optimization:
    _type: nat_toolkit/show_last_optimization

# LLM configuration for grid optimization agents
llms:
  grid_optimization_llm:
    _type: openai
    model_name: gpt-4o-mini
    temperature: 0.1
    max_tokens: 1024

# Main workflow configuration
workflow:
  _type: react_agent
  tool_names:
    - optimize_grid
    - show_last_optimization
    - current_datetime
  llm_name: grid_optimization_llm
  verbose: true
  system_message: |
    You are a comprehensive grid optimization assistant. You can:
    1. Optimize grid supply for any region using optimize_grid
    2. Show the latest optimization results using show_last_optimization
    3. Provide analysis and recommendations
    
    Available regions: us-west, us-east, us-central, pgae