# Simple Grid Optimization Configuration
# Basic NAT setup with minimal configuration for quick testing
# Status: ⚠️ Requires OpenAI API key for LLM features  
# Features: current_datetime, optimize_grid

general:
  use_uvloop: true

# Functions available
functions:
  current_datetime:
    _type: current_datetime
    description: "Get current date and time"
  optimize_grid:
    _type: nat_toolkit/optimize_grid
    description: "Optimize power grid for specified region"
    
# LLM configuration
llms:
  grid_optimization_llm:
    _type: openai
    model_name: gpt-4o-mini
    temperature: 0.1
    max_tokens: 1024

# Simple workflow configuration
workflow:
  _type: react_agent
  tool_names:
    - current_datetime
    - optimize_grid
  llm_name: grid_optimization_llm
  verbose: true
  system_message: |
    You are a simple grid optimization assistant. Always start by checking the current time, then optimize power grids.
    Available regions: us-west, us-east, us-central, pgae