# Simplified NAT configuration for Grid Optimization System
# Using built-in tools first, then we can add custom ones

general:
  use_uvloop: true

# Basic built-in functions
functions:
  code_execution:
    _type: code_execution
    
# LLM configuration
llms:
  grid_optimization_llm:
    _type: openai
    model_name: gpt-4
    temperature: 0.1
    max_tokens: 2048

# Simple workflow configuration using just tools
workflow:
  _type: code_execution