# NVIDIA NeMo Agent Toolkit - Advanced Reasoning Configuration
# For complex grid optimization scenarios requiring detailed analysis

general:
  use_uvloop: true

# LLM Configuration optimized for reasoning tasks
llms:
  # Primary reasoning model
  reasoning_llm:
    _type: openai
    model_name: gpt-4o
    max_tokens: 8192
    temperature: 0.0  # Deterministic for consistent reasoning
    
  # Analysis model for complex computations
  analysis_llm:
    _type: openai
    model_name: gpt-4o-mini
    max_tokens: 4096
    temperature: 0.1
    
  # NVIDIA NIM option for high-performance reasoning
  nim_reasoning_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0
    max_tokens: 4096

# NAT Grid Optimization Functions (same as basic config)
functions:
  grid_optimize:
    _type: nat_grid_toolkit/grid_optimize
    description: "Optimize power grid configuration with detailed reasoning"
    
  grid_status:
    _type: nat_grid_toolkit/grid_status
    description: "Comprehensive grid status analysis"
    
  grid_analyze:
    _type: nat_grid_toolkit/grid_analyze
    description: "Deep performance analysis with reasoning"
    
  current_datetime:
    _type: current_datetime

# Advanced Reasoning Agent Workflow
workflow:
  _type: reasoning_agent
  tool_names:
    - grid_optimize
    - grid_status
    - grid_analyze
    - current_datetime
  llm_name: reasoning_llm
  reasoning_model_name: analysis_llm
  max_iterations: 12
  verbose: true
  parse_agent_response_max_retries: 5
  
  # Enhanced system message for reasoning scenarios
  system_message: |
    You are an expert power grid optimization specialist with advanced analytical reasoning capabilities.
    
    For complex grid optimization scenarios, follow this systematic approach:
    
    PHASE 1 - SITUATION ASSESSMENT:
    - Gather current grid status and historical performance data
    - Identify constraints, regulations, and safety requirements
    - Assess environmental and economic factors
    
    PHASE 2 - ANALYSIS & PLANNING:
    - Analyze multiple optimization strategies and their trade-offs
    - Model potential outcomes and risk scenarios
    - Consider both short-term and long-term implications
    
    PHASE 3 - IMPLEMENTATION STRATEGY:
    - Design step-by-step implementation plan
    - Identify monitoring points and success metrics
    - Plan contingency actions for unexpected results
    
    PHASE 4 - EXECUTION & VALIDATION:
    - Execute optimization with continuous monitoring
    - Validate results against expected outcomes
    - Document lessons learned and recommendations
    
    Always provide detailed reasoning for your decisions and explain the methodology
    behind your optimization strategies. Consider grid stability, economic efficiency,
    environmental impact, and regulatory compliance in all recommendations.