# Primary Grid Optimization Configuration
# NVIDIA NeMo Agent Toolkit workflow with grid optimization functions
# Status: ⚠️ Requires OpenAI API key for LLM features
# Alternative: Use run_grid_optimization.py for direct access

general:
  use_uvloop: true

# Large Language Models Configuration  
llms:
  # Primary LLM for grid optimization tasks
  grid_llm:
    _type: openai
    model_name: gpt-4o
    max_tokens: 4096
    temperature: 0.1
    
  # Backup LLM for fallback scenarios
  backup_llm:
    _type: openai
    model_name: gpt-4o-mini
    max_tokens: 2048
    temperature: 0.1
    
  # NVIDIA NIM LLM option (requires NVIDIA API key)
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0
    max_tokens: 2048

# Available Functions
functions:
  current_datetime:
    _type: current_datetime
    description: "Get current date and time for grid optimization timestamping"
  optimize_grid:
    _type: nat_toolkit/optimize_grid
    description: "Optimize power grid for specified region"

# Main Workflow Definition  
workflow:
  _type: react_agent
  tool_names:
    - optimize_grid
    - current_datetime
  llm_name: grid_llm
  verbose: true
  system_message: |
    You are a grid optimization assistant. Help users optimize power grids for different regions.
    Use optimize_grid to perform optimizations and current_datetime for timestamping.
    Available regions: us-west, us-east, us-central, pgae
